### ISSUE TITLE
登录没mock数据

### ISSUE THREAD

**Issue by Axu96** [lgf196/ant-simple-pro#43]
![image](https://user-images.githubusercontent.com/28865316/164205830-39d6f33e-462a-44b0-a1a2-6cf620beaf3f.png)
登录没mock数据 也不知道要什么数据格式特别是菜单那块  绕过鉴权进去也看不到菜单

**Comment by lgf196** [comment]
我这边是可以登录进来的，或者你不要用https访问

**Comment by Axu96** [comment]
登录数据哪里来的呢  没找到mock相关的东西呢

**Comment by Axu96** [comment]
> 我这边是可以登录进来的，或者你不要用https访问

登录数据哪里来的呢 没找到mock相关的东西呢

**Comment by lgf196** [comment]
![image](https://user-images.githubusercontent.com/29600558/164382019-d6b92d39-0c2b-408d-adbf-9a38a0bec451.png)
有后端接口数据的，我们不用mock，后端代码在分支`after`中，后端代码用`ts`+`node`写的，而且我们也提供了一个测试服的ip,直接切换即可，如果想本地启动项目，可以将我们后端代码拉下来，运行，电脑必须的装`mysql`,等，具体请查看[文档](http://blog.lgf196.top/ant-simple-pro-document/guide/advanced/afterEnd.html#%E8%BF%90%E8%A1%8C%E9%A1%B9%E7%9B%AE)

**Comment by Axu96** [comment]
> ![image](https://user-images.githubusercontent.com/29600558/164382019-d6b92d39-0c2b-408d-adbf-9a38a0bec451.png) 有后端接口数据的，我们不用mock，后端代码在分支`after`中，后端代码用`ts`+`node`写的，而且我们也提供了一个测试服的ip,直接切换即可，如果想本地启动项目，可以将我们后端代码拉下来，运行，电脑必须的装`mysql`,等，具体请查看[文档](http://blog.lgf196.top/ant-simple-pro-document/guide/advanced/afterEnd.html#%E8%BF%90%E8%A1%8C%E9%A1%B9%E7%9B%AE)

ok 谢谢
