### ISSUE TITLE
啥玩意啊，跑起来全是报错

### ISSUE THREAD

**Issue by ghost** [lgf196/ant-simple-pro#47]
![image](https://user-images.githubusercontent.com/88129747/186805443-537308a0-bee3-4ba6-a457-ba8b7601accb.png)
首页都报错， 本地启动的代理地址也是错的， 菜单里面点几个错几个。  压根就跑不起来

**Comment by lgf196** [comment]
https://lgf196.top/react/login
https://lgf196.top/vue/
将请求地址换成：https://lgf196.top即可
